In [2]:
import pandas as pd

In [3]:
dataframes = pd.read_html("https://en.wikipedia.org/wiki/Relation_(database)",header=0)

In [4]:
len(dataframes)

2

In [5]:
dataframes[0].head()

   ID (Integer)       Name (String)    Address (String)
0           102    Yonezawa Akinori       Naha, Okinawa
1           202       Murata Makoto      Sendai, Miyagi
2           104        Sakamura Ken  Kumamoto, Kumamoto
3           152  Matsumoto Yukihiro    Okinawa, Okinawa

In [6]:
dataframes = pd.read_html("http://www.basketball-reference.com/draft/NBA_2017.html")

dataframes

[   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                    Rk                 Pk                 Tm
 0                   1                  1                PHI
 1                   2                  2                LAL
 2                   3                  3                BOS
 3                   4                  4                PHO
 4                   5                  5                SAC
 5                   6                  6                ORL
 6                   7                  7                MIN
 7                   8                  8                NYK
 8                   9                  9                DAL
 9                  10                 10                SAC
 10                 11                 11                CHO
 11                 12                 12                DET
 12                 13                 13                DEN
 13                 14                 14                MIA
 14                 15                 15                POR
 15                 16                 16                CHI
 16                 17                 17                MIL
 17                 18                 18                IND
 18                 19                 19                ATL
 19                 20                 20                POR
 20                 21                 21                OKC
 21                 22                 22                BRK
 22                 23                 23                TOR
 23                 24                 24                UTA
 24                 25                 25                ORL
 25                 26                 26                POR
 26                 27                 27                BRK
 27                 28                 28                LAL
 28                 29                 29                SAS
 29                 30                 30                UTA
 ..                ...                ...                ...
 32                 31                 31                CHO
 33                 32                 32                PHO
 34                 33                 33                ORL
 35                 34                 34                SAC
 36                 35                 35                ORL
 37                 36                 36                PHI
 38                 37                 37                BOS
 39                 38                 38                CHI
 40                 39                 39                PHI
 41                 40                 40                NOP
 42                 41                 41                ATL
 43                 42                 42                UTA
 44                 43                 43                HOU
 45                 44                 44                NYK
 46                 45                 45                HOU
 47                 46                 46                PHI
 48                 47                 47                IND
 49                 48                 48                MIL
 50                 49                 49                DEN
 51                 50                 50                PHI
 52                 51                 51                DEN
 53                 52                 52                NOP
 54                 53                 53                BOS
 55                 54                 54                PHO
 56                 55                 55                UTA
 57                 56                 56                BOS
 58                 57                 57                BRK
 59                 58                 58                NYK
 60                 59                 59                SAS
 61                 60                 60                ATL

                 Round 1                     Unnamed: 4_level_0 Totals  \
                  Player                                College    Yrs
 0        Markelle Fultz               University of Washington      1
 1            Lonzo Ball  University of California, Los Angeles      1
 2          Jayson Tatum                        Duke University      1
 3          Josh Jackson                   University of Kansas      1
 4          De'Aaron Fox                 University of Kentucky      1
 5        Jonathan Isaac               Florida State University      1
 6       Lauri Markkanen                  University of Arizona      1
 7       Frank Ntilikina                                    NaN      1
 8          Dennis Smith        North Carolina State University      1
 9          Zach Collins                     Gonzaga University      1
 10           Malik Monk                 University of Kentucky      1
 11         Luke Kennard                        Duke University      1
 12     Donovan Mitchell               University of Louisville      1
 13          Bam Adebayo                 University of Kentucky      1
 14       Justin Jackson           University of North Carolina      1
 15        Justin Patton                   Creighton University      1
 16          D.J. Wilson                 University of Michigan      1
 17            T.J. Leaf  University of California, Los Angeles      1
 18         John Collins                 Wake Forest University      1
 19          Harry Giles                        Duke University    NaN
 20    Terrance Ferguson                                    NaN      1
 21        Jarrett Allen          University of Texas at Austin      1
 22           OG Anunoby                     Indiana University      1
 23          Tyler Lydon                    Syracuse University      1
 24     Anzejs Pasecniks                                    NaN    NaN
 25       Caleb Swanigan                      Purdue University      1
 26           Kyle Kuzma                     University of Utah      1
 27         Tony Bradley           University of North Carolina      1
 28        Derrick White                 University of Colorado      1
 29            Josh Hart                   Villanova University      1
 ..                  ...                                    ...    ...
 32        Frank Jackson                        Duke University    NaN
 33           Davon Reed                    University of Miami      1
 34        Wesley Iwundu                Kansas State University      1
 35          Frank Mason                   University of Kansas      1
 36            Ivan Rabb               University of California      1
 37         Jonah Bolden                                    NaN    NaN
 38         Semi Ojeleye          Southern Methodist University      1
 39          Jordan Bell                   University of Oregon      1
 40          Jawun Evans              Oklahoma State University      1
 41         Dwayne Bacon               Florida State University      1
 42         Tyler Dorsey                   University of Oregon      1
 43        Thomas Bryant                     Indiana University      1
 44   Isaiah Hartenstein                                    NaN    NaN
 45       Damyean Dotson                   University of Oregon      1
 46        Dillon Brooks                   University of Oregon      1
 47       Sterling Brown          Southern Methodist University      1
 48         Ike Anigbogu  University of California, Los Angeles      1
 49  Sindarius Thornwell           University of South Carolina      1
 50        Vlatko Cancar                                    NaN    NaN
 51      Mathias Lessort                                    NaN    NaN
 52         Monte Morris                  Iowa State University      1
 53        Edmond Sumner                      Xavier University      1
 54         Kadeem Allen                  University of Arizona      1
 55          Alec Peters                  Valparaiso University      1
 56  Nigel Williams-Goss                     Gonzaga University    NaN
 57          Jabari Bird               University of California      1
 58  Aleksandar Vezenkov                                    NaN    NaN
 59       Ognjen Jaramaz                                    NaN    NaN
 60    Jaron Blossomgame                     Clemson University    NaN
 61           Alpha Kaba                                    NaN    NaN

    Shooting Per Game Advanced Unnamed: 9_level_0         ...          \
           G       MP      PTS                TRB         ...
 0        14      253      100                 43         ...
 1        52     1780      528                360         ...
 2        80     2438     1112                402         ...
 3        77     1959     1012                351         ...
 4        73     2026      844                204         ...
 5        27      536      145                 99         ...
 6        68     2020     1033                508         ...
 7        78     1706      463                177         ...
 8        69     2049     1048                260         ...
 9        66     1045      292                221         ...
 10       63      854      421                 66         ...
 11       73     1463      558                176         ...
 12       79     2638     1616                296         ...
 13       69     1368      477                381         ...
 14       68     1506      453                187         ...
 15        1        4        2                  0         ...
 16       22       71       21                 10         ...
 17       53      459      156                 82         ...
 18       74     1785      777                541         ...
 19      NaN      NaN      NaN                NaN         ...
 20       61      763      189                 47         ...
 21       72     1441      587                388         ...
 22       74     1481      438                184         ...
 23        1        2        0                  0         ...
 24      NaN      NaN      NaN                NaN         ...
 25       27      189       61                 54         ...
 26       77     2401     1242                483         ...
 27        9       29        8                 11         ...
 28       17      139       54                 26         ...
 29       63     1461      496                263         ...
 ..      ...      ...      ...                ...         ...
 32      NaN      NaN      NaN                NaN         ...
 33       21      242       63                 39         ...
 34       62     1020      229                137         ...
 35       52      984      413                130         ...
 36       36      516      201                158         ...
 37      NaN      NaN      NaN                NaN         ...
 38       73     1150      195                161         ...
 39       57      809      262                207         ...
 40       48      778      231                 84         ...
 41       53      713      175                124         ...
 42       56      974      405                130         ...
 43       15       72       22                 17         ...
 44      NaN      NaN      NaN                NaN         ...
 45       44      474      182                 84         ...
 46       82     2350      898                257         ...
 47       54      776      217                143         ...
 48       11       30       13                  9         ...
 49       73     1156      282                140         ...
 50      NaN      NaN      NaN                NaN         ...
 51      NaN      NaN      NaN                NaN         ...
 52        3       25       10                  2         ...
 53        1        2        2                  1         ...
 54       18      107       19                 11         ...
 55       20      225       82                 37         ...
 56      NaN      NaN      NaN                NaN         ...
 57       13      115       39                 19         ...
 58      NaN      NaN      NaN                NaN         ...
 59      NaN      NaN      NaN                NaN         ...
 60      NaN      NaN      NaN                NaN         ...
 61      NaN      NaN      NaN                NaN         ...

    Unnamed: 12_level_0 Unnamed: 13_level_0 Unnamed: 14_level_0  \
                    3P%                 FT%                  MP
 0                 .000                .476                18.1
 1                 .305                .451                34.2
 2                 .434                .826                30.5
 3                 .263                .634                25.4
 4                 .307                .723                27.8
 5                 .348                .760                19.9
 6                 .362                .843                29.7
 7                 .318                .721                21.9
 8                 .313                .694                29.7
 9                 .310                .643                15.8
 10                .342                .842                13.6
 11                .415                .855                20.0
 12                .340                .805                33.4
 13                .000                .721                19.8
 14                .308                .722                22.1
 15                 NaN                 NaN                 4.0
 16                .400                .500                 3.2
 17                .429                .625                 8.7
 18                .340                .715                24.1
 19                 NaN                 NaN                 NaN
 20                .333                .900                12.5
 21                .333                .776                20.0
 22                .371                .629                20.0
 23                 NaN                 NaN                 2.0
 24                 NaN                 NaN                 NaN
 25                .125                .667                 7.0
 26                .366                .707                31.2
 27                .000               1.000                 3.2
 28                .615                .700                 8.2
 29                .396                .702                23.2
 ..                 ...                 ...                 ...
 32                 NaN                 NaN                 NaN
 33                .289                .667                11.5
 34                .196                .723                16.5
 35                .360                .817                18.9
 36                 NaN                .806                14.3
 37                 NaN                 NaN                 NaN
 38                .320                .610                15.8
 39                .000                .682                14.2
 40                .278                .776                16.2
 41                .256                .800                13.5
 42                .360                .714                17.4
 43                .100                .556                 4.8
 44                 NaN                 NaN                 NaN
 45                .324                .696                10.8
 46                .356                .747                28.7
 47                .352                .875                14.4
 48                 NaN                .833                 2.7
 49                .377                .670                15.8
 50                 NaN                 NaN                 NaN
 51                 NaN                 NaN                 NaN
 52                .000               1.000                 8.3
 53                 NaN                 NaN                 2.0
 54                .000                .778                 5.9
 55                .310                .800                11.3
 56                 NaN                 NaN                 NaN
 57                .429                .462                 8.8
 58                 NaN                 NaN                 NaN
 59                 NaN                 NaN                 NaN
 60                 NaN                 NaN                 NaN
 61                 NaN                 NaN                 NaN

    Unnamed: 15_level_0 Unnamed: 16_level_0 Unnamed: 17_level_0  \
                    PTS                 TRB                 AST
 0                  7.1                 3.1                 3.8
 1                 10.2                 6.9                 7.2
 2                 13.9                 5.0                 1.6
 3                 13.1                 4.6                 1.5
 4                 11.6                 2.8                 4.4
 5                  5.4                 3.7                 0.7
 6                 15.2                 7.5                 1.2
 7                  5.9                 2.3                 3.2
 8                 15.2                 3.8                 5.2
 9                  4.4                 3.3                 0.8
 10                 6.7                 1.0                 1.4
 11                 7.6                 2.4                 1.7
 12                20.5                 3.7                 3.7
 13                 6.9                 5.5                 1.5
 14                 6.7                 2.8                 1.1
 15                 2.0                 0.0                 0.0
 16                 1.0                 0.5                 0.1
 17                 2.9                 1.5                 0.2
 18                10.5                 7.3                 1.3
 19                 NaN                 NaN                 NaN
 20                 3.1                 0.8                 0.3
 21                 8.2                 5.4                 0.7
 22                 5.9                 2.5                 0.7
 23                 0.0                 0.0                 0.0
 24                 NaN                 NaN                 NaN
 25                 2.3                 2.0                 0.5
 26                16.1                 6.3                 1.8
 27                 0.9                 1.2                 0.1
 28                 3.2                 1.5                 0.5
 29                 7.9                 4.2                 1.3
 ..                 ...                 ...                 ...
 32                 NaN                 NaN                 NaN
 33                 3.0                 1.9                 0.6
 34                 3.7                 2.2                 0.9
 35                 7.9                 2.5                 2.8
 36                 5.6                 4.4                 0.9
 37                 NaN                 NaN                 NaN
 38                 2.7                 2.2                 0.3
 39                 4.6                 3.6                 1.8
 40                 4.8                 1.8                 2.1
 41                 3.3                 2.3                 0.7
 42                 7.2                 2.3                 1.4
 43                 1.5                 1.1                 0.4
 44                 NaN                 NaN                 NaN
 45                 4.1                 1.9                 0.7
 46                11.0                 3.1                 1.6
 47                 4.0                 2.6                 0.5
 48                 1.2                 0.8                 0.0
 49                 3.9                 1.9                 0.9
 50                 NaN                 NaN                 NaN
 51                 NaN                 NaN                 NaN
 52                 3.3                 0.7                 2.3
 53                 2.0                 1.0                 0.0
 54                 1.1                 0.6                 0.7
 55                 4.1                 1.9                 0.6
 56                 NaN                 NaN                 NaN

In [7]:
len(dataframes)

1

In [69]:
dataframes[0].columns

MultiIndex(levels=[['Advanced', 'Per Game', 'Round 1', 'Shooting', 'Totals', 'Unnamed: 0_level_0', 'Unnamed: 10_level_0', 'Unnamed: 11_level_0', 'Unnamed: 12_level_0', 'Unnamed: 13_level_0', 'Unnamed: 14_level_0', 'Unnamed: 15_level_0', 'Unnamed: 16_level_0', 'Unnamed: 17_level_0', 'Unnamed: 18_level_0', 'Unnamed: 19_level_0', 'Unnamed: 1_level_0', 'Unnamed: 20_level_0', 'Unnamed: 21_level_0', 'Unnamed: 2_level_0', 'Unnamed: 4_level_0', 'Unnamed: 9_level_0'], ['3P%', 'AST', 'BPM', 'College', 'FG%', 'FT%', 'G', 'MP', 'PTS', 'Pk', 'Player', 'Rk', 'TRB', 'Tm', 'VORP', 'WS', 'WS/48', 'Yrs']],
           labels=[[5, 16, 19, 2, 20, 4, 3, 1, 0, 21, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18], [11, 9, 13, 10, 3, 17, 6, 7, 8, 12, 1, 4, 0, 5, 7, 8, 12, 1, 15, 16, 2, 14]])

In [8]:
dx = dataframes[0]
dx

,Unnamed: 0_level_0,Unnamed: 1_level_0,Unnamed: 2_level_0,Round 1,Unnamed: 4_level_0,Totals,Shooting,Per Game,Advanced,Unnamed: 9_level_0,...,Unnamed: 12_level_0,Unnamed: 13_level_0,Unnamed: 14_level_0,Unnamed: 15_level_0,Unnamed: 16_level_0,Unnamed: 17_level_0,Unnamed: 18_level_0,Unnamed: 19_level_0,Unnamed: 20_level_0,Unnamed: 21_level_0
,Rk,Pk,Tm,Player,College,Yrs,G,MP,PTS,TRB,...,3P%,FT%,MP,PTS,TRB,AST,WS,WS/48,BPM,VORP
0,1,1,PHI,Markelle Fultz,University of Washington,1,14,253,100,43,...,.000,.476,18.1,7.1,3.1,3.8,0.2,.043,-3.0,-0.1
1,2,2,LAL,Lonzo Ball,"University of California, Los Angeles",1,52,1780,528,360,...,.305,.451,34.2,10.2,6.9,7.2,2.0,.053,1.7,1.7
2,3,3,BOS,Jayson Tatum,Duke University,1,80,2438,1112,402,...,.434,.826,30.5,13.9,5.0,1.6,7.1,.139,1.0,1.8
3,4,4,PHO,Josh Jackson,University of Kansas,1,77,1959,1012,351,...,.263,.634,25.4,13.1,4.6,1.5,-0.7,-.018,-4.3,-1.1
4,5,5,SAC,De'Aaron Fox,University of Kentucky,1,73,2026,844,204,...,.307,.723,27.8,11.6,2.8,4.4,-0.6,-.014,-4.4,-1.2
5,6,6,ORL,Jonathan Isaac,Florida State University,1,27,536,145,99,...,.348,.760,19.9,5.4,3.7,0.7,0.2,.021,-1.8,0.0
6,7,7,MIN,Lauri Markkanen,University of Arizona,1,68,2020,1033,508,...,.362,.843,29.7,15.2,7.5,1.2,3.3,.079,-1.9,0.1
7,8,8,NYK,Frank Ntilikina,NaN,1,78,1706,463,177,...,.318,.721,21.9,5.9,2.3,3.2,-0.9,-.026,-3.9,-0.8
8,9,9,DAL,Dennis Smith,North Carolina State University,1,69,2049,1048,260,...,.313,.694,29.7,15.2,3.8,5.2,-0.7,-.017,-2.3,-0.1
9,10,10,SAC,Zach Collins,Gonzaga University,1,66,1045,292,221,...,.310,.643,15.8,4.4,3.3,0.8,0.6,.030,-3.2,-0.3
10,11,11,CHO,Malik Monk,University of Kentucky,1,63,854,421,66,...,.342,.842,13.6,6.7,1.0,1.4,0.0,.001,-4.4,-0.5
11,12,12,DET,Luke Kennard,Duke University,1,73,1463,558,176,...,.415,.855,20.0,7.6,2.4,1.7,2.6,.085,-1.5,0.2
12,13,13,DEN,Donovan Mitchell,University of Louisville,1,79,2638,1616,296,...,.340,.805,33.4,20.5,3.7,3.7,5.2,.095,1.1,2.1
13,14,14,MIA,Bam Adebayo,University of Kentucky,1,69,1368,477,381,...,.000,.721,19.8,6.9,5.5,1.5,4.2,.148,0.2,0.8
14,15,15,POR,Justin Jackson,University of North Carolina,1,68,1506,453,187,...,.308,.722,22.1,6.7,2.8,1.1,1.0,.031,-3.5,-0.6
15,16,16,CHI,Justin Patton,Creighton University,1,1,4,2,0,...,NaN,NaN,4.0,2.0,0.0,0.0,0.0,.151,3.3,0.0
16,17,17,MIL,D.J. Wilson,University of Michigan,1,22,71,21,10,...,.400,.500,3.2,1.0,0.5,0.1,0.1,.054,-4.1,0.0
17,18,18,IND,T.J. Leaf,"University of California, Los Angeles",1,53,459,156,82,...,.429,.625,8.7,2.9,1.5,0.2,0.8,.082,-4.8,-0.3
18,19,19,ATL,John Collins,Wake Forest University,1,74,1785,777,541,...,.340,.715,24.1,10.5,7.3,1.3,5.4,.145,1.7,1.7
19,20,20,POR,Harry Giles,Duke University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,21,OKC,Terrance Ferguson,NaN,1,61,763,189,47,...,.333,.900,12.5,3.1,0.8,0.3,1.2,.077,-2.5,-0.1
21,22,22,BRK,Jarrett Allen,University of Texas at Austin,1,72,1441,587,388,...,.333,.776,20.0,8.2,5.4,0.7,4.2,.141,0.2,0.8
22,23,23,TOR,OG Anunoby,Indiana University,1,74,1481,438,184,...,.371,.629,20.0,5.9,2.5,0.7,3.0,.098,0.6,1.0
23,24,24,UTA,Tyler Lydon,Syracuse University,1,1,2,0,0,...,NaN,NaN,2.0,0.0,0.0,0.0,0.0,-.014,-6.5,0.0
24,25,25,ORL,Anzejs Pasecniks,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,26,POR,Caleb Swanigan,Purdue University,1,27,189,61,54,...,.125,.667,7.0,2.3,2.0,0.5,0.0,-.003,-5.4,-0.2
26,27,27,BRK,Kyle Kuzma,University of Utah,1,77,2401,1242,483,...,.366,.707,31.2,16.1,6.3,1.8,3.8,.077,-1.3,0.4
27,28,28,LAL,Tony Bradley,University of North Carolina,1,9,29,8,11,...,.000,1.000,3.2,0.9,1.2,0.1,0.0,.033,-9.6,-0.1
28,29,29,SAS,Derrick White,University of Colorado,1,17,139,54,26,...,.615,.700,8.2,3.2,1.5,0.5,0.5,.170,0.5,0.1
29,30,30,UTA,Josh Hart,Villanova University,1,63,1461,496,263,...,.396,.702,23.2,7.9,4.2,1.3,3.4,.111,-0.1,0.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,31,31,CHO,Frank Jackson,Duke University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,32,32,PHO,Davon Reed,University of Miami,1,21,242,63,39,...,.289,.667,11.5,3.0,1.9,0.6,-0.3,-.059,-6.7,-0.3
34,33,33,ORL,Wesley Iwundu,Kansas State University,1,62,1020,229,137,...,.196,.723,16.5,3.7,2.2,0.9,0.7,.032,-3.5,-0.4
35,34,34,SAC,Frank Mason,University of Kansas,1,52,984,413,130,...,.360,.817,18.9,7.9,2.5,2.8,0.5,.027,-3.4,-0.4
36,35,35,ORL,Ivan Rabb,University of California,1,36,516,201,158,...,NaN,.806,14.3,5.6,4.4,0.9,1.2,.109,-1.5,0.1
37,36,36,PHI,Jonah Bolden,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,37,37,BOS,Semi Ojeleye,Southern Methodist University,1,73,1150,195,161,...,.320,.610,15.8,2.7,2.2,0.3,1.2,.048,-3.5,-0.4
39,38,38,CHI,Jordan Bell,University of Oregon,1,57,809,262,207,...,.000,.682,14.2,4.6,3.6,1.8,2.9,.174,3.7,1.2
40,39,39,PHI,Jawun Evans,Oklahoma State University,1,48,778,231,84,...,.278,.776,16.2,4.8,1.8,2.1,-0.2,-.011,-4.7,-0.5
41,40,40,NOP,Dwayne Bacon,Florida State University,1,53,713,175,124,...,.256,.800,13.5,3.3,2.3,0.7,-0.1,-.007,-5.7,-0.7
42,41,41,ATL,Tyler Dorsey,University of Oregon,1,56,974,405,130,...,.360,.714,17.4,7.2,2.3,1.4,0.4,.019,-4.3,-0.6
43,42,42,UTA,Thomas Bryant,Indiana University,1,15,72,22,17,...,.100,.556,4.8,1.5,1.1,0.4,0.1,.050,-4.2,0.0
44,43,43,HOU,Isaiah Hartenstein,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,44,44,NYK,Damyean Dotson,University of Oregon,1,44,474,182,84,...,.324,.696,10.8,4.1,1.9,0.7,0.6,.060,-3.1,-0.1
46,45,45,HOU,Dillon Brooks,University of Oregon,1,82,2350,898,257,...,.356,.747,28.7,11.0,3.1,1.6,1.2,.024,-3.1,-0.7
47,46,46,PHI,Sterling Brown,Southern Methodist University,1,54,776,217,143,...,.352,.875,14.4,4.0,2.6,0.5,0.7,.043,-4.0,-0.4
48,47,47,IND,Ike Anigbogu,"University of California, Los Angeles",1,11,30,13,9,...,NaN,.833,2.7,1.2,0.8,0.0,0.1,.165,-5.4,0.0
49,48,48,MIL,Sindarius Thornwell,University of South Carolina,1,73,1156,282,140,...,.377,.670,15.8,3.9,1.9,0.9,1.0,.041,-1.6,0.1
50,49,49,DEN,Vlatko Cancar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,50,50,PHI,Mathias Lessort,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,51,51,DEN,Monte Morris,Iowa State University,1,3,25,10,2,...,.000,1.000,8.3,3.3,0.7,2.3,0.2,.312,2.0,0.0
53,52,52,NOP,Edmond Sumner,Xavier University,1,1,2,2,1,...,NaN,NaN,2.0,2.0,1.0,0.0,0.0,.425,-5.3,0.0
54,53,53,BOS,Kadeem Allen,University of Arizona,1,18,107,19,11,...,.000,.778,5.9,1.1,0.6,0.7,-0.1,-.039,-6.4,-0.1
55,54,54,PHO,Alec Peters,Valparaiso University,1,20,225,82,37,...,.310,.800,11.3,4.1,1.9,0.6,0.3,.055,-3.3,-0.1
56,55,55,UTA,Nigel Williams-Goss,Gonzaga University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,56,56,BOS,Jabari Bird,University of California,1,13,115,39,19,...,.429,.462,8.8,3.0,1.5,0.6,0.2,.098,-2.1,0.0
58,57,57,BRK,Aleksandar Vezenkov,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,58,58,NYK,Ognjen Jaramaz,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,59,59,SAS,Jaron Blossomgame,Clemson University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,60,60,ATL,Alpha Kaba,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
index = dx.columns

In [72]:
index

MultiIndex(levels=[['Advanced', 'Per Game', 'Round 1', 'Shooting', 'Totals', 'Unnamed: 0_level_0', 'Unnamed: 10_level_0', 'Unnamed: 11_level_0', 'Unnamed: 12_level_0', 'Unnamed: 13_level_0', 'Unnamed: 14_level_0', 'Unnamed: 15_level_0', 'Unnamed: 16_level_0', 'Unnamed: 17_level_0', 'Unnamed: 18_level_0', 'Unnamed: 19_level_0', 'Unnamed: 1_level_0', 'Unnamed: 20_level_0', 'Unnamed: 21_level_0', 'Unnamed: 2_level_0', 'Unnamed: 4_level_0', 'Unnamed: 9_level_0'], ['3P%', 'AST', 'BPM', 'College', 'FG%', 'FT%', 'G', 'MP', 'PTS', 'Pk', 'Player', 'Rk', 'TRB', 'Tm', 'VORP', 'WS', 'WS/48', 'Yrs']],
           labels=[[5, 16, 19, 2, 20, 4, 3, 1, 0, 21, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18], [11, 9, 13, 10, 3, 17, 6, 7, 8, 12, 1, 4, 0, 5, 7, 8, 12, 1, 15, 16, 2, 14]])

In [73]:
dataframes[0].head()

,Unnamed: 0_level_0,Unnamed: 1_level_0,Unnamed: 2_level_0,Round 1,Unnamed: 4_level_0,Totals,Shooting,Per Game,Advanced,Unnamed: 9_level_0,...,Unnamed: 12_level_0,Unnamed: 13_level_0,Unnamed: 14_level_0,Unnamed: 15_level_0,Unnamed: 16_level_0,Unnamed: 17_level_0,Unnamed: 18_level_0,Unnamed: 19_level_0,Unnamed: 20_level_0,Unnamed: 21_level_0
,Rk,Pk,Tm,Player,College,Yrs,G,MP,PTS,TRB,...,3P%,FT%,MP,PTS,TRB,AST,WS,WS/48,BPM,VORP
0,1,1,PHI,Markelle Fultz,University of Washington,1,4,76,24,9,...,NaN,.500,19.0,6.0,2.3,1.8,-0.1,-.085,-9.9,-0.2
1,2,2,LAL,Lonzo Ball,"University of California, Los Angeles",1,36,1222,367,257,...,.303,.480,33.9,10.2,7.1,7.1,1.0,.041,1.0,0.9
2,3,3,BOS,Jayson Tatum,Duke University,1,58,1796,787,298,...,.431,.823,31.0,13.6,5.1,1.4,5.5,.147,1.1,1.4
3,4,4,PHO,Josh Jackson,University of Kansas,1,56,1305,617,227,...,.259,.607,23.3,11.0,4.1,1.2,-1.1,-.039,-5.5,-1.2
4,5,5,SAC,De'Aaron Fox,University of Kentucky,1,48,1303,543,126,...,.326,.730,27.1,11.3,2.6,4.3,-0.5,-.018,-4.7,-0.9

In [74]:
dataframes[0].xs('MP',level=1,axis=1,drop_level=False)

   Per Game Unnamed: 14_level_0
         MP                  MP
0        76                19.0
1      1222                33.9
2      1796                31.0
3      1305                23.3
4      1303                27.1
5       285                19.0
6      1518                30.4
7      1114                20.3
8      1437                29.3
9       632                15.4
10      485                12.1
11      913                18.6
12     1728                32.0
13      966                20.6
14      771                18.8
15      NaN                 NaN
16       60                 3.3
17      398                 9.5
18     1130                22.2
19      NaN                 NaN
20      526                12.5
21      892                18.2
22     1156                21.0
23        2                 2.0
24      NaN                 NaN
25      139                 8.2
26     1609                29.8
27       28                 3.5
28      117                 7.8
29     1028                20.6
..      ...                 ...
32      NaN                 NaN
33       56                 8.0
34      544                14.3
35      539                18.6
36      177                11.1
37      NaN                 NaN
38      722                14.2
39      546                14.4
40      701                18.4
41      470                13.4
42      374                12.1
43       19                 3.2
44      NaN                 NaN
45      225                 8.7
46     1537                27.9
47      434                14.5
48       28                 2.8
49      637                13.0
50      NaN                 NaN
51      NaN                 NaN
52       25                12.5
53      NaN                 NaN
54       27                 3.9
55       81                 9.0
56      NaN                 NaN
57       22                 5.5
58      NaN                 NaN
59      NaN                 NaN
60      NaN                 NaN
61      NaN                 NaN

[62 rows x 2 columns]